name: Build installers

on:
  push:
    branches: [main]
    tags: ["v*"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }} (Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        python-version: ["3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --name "ShotCanvas" --windowed main.py
      - name: Create DMG (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          APP_NAME="ShotCanvas.app"
          APP_PATH="dist/ShotCanvas/${APP_NAME}"
          mkdir -p pkg
          # Applications로 심볼릭 링크(일반적인 DMG UX)
          ln -s /Applications pkg/Applications || true
          cp -R "${APP_PATH}" pkg/
          hdiutil create -volname "ShotCanvas" -srcfolder pkg -ov -format UDZO ShotCanvas.dmg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ShotCanvas-${{ matrix.os }}
          path: |
            dist/**
            ShotCanvas.dmg

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**


